// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdqconymyzluyruabnzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkcWNvbnlteXpsdXlydWFibnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTMyMTEsImV4cCI6MjA2Nzg2OTIxMX0._17pe9Xwk7gY2Jw3w0DGc-RaKyL5vsQpQkuSPez6ANI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});